import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout_1 from "@/layouts/layout-1/Layout_1";
import Header from "../../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {/* <main className=""> */}
            {children}
          {/* </main> */}
      </body>
    </html>
  );
}
